Repository Michigan-State-University/cias-web, pull requests merged in 2023-06, with the labels that each got.

#3 replace deprecating set-output command
  .github/workflows/main.yml
Labels: APPROVED

#1 [CIAS30-3342] Create collaboration UI components
  app/components/AppRoute/index.js
  app/components/AppRoute/styled.js
  app/components/AppRoute/tests/__snapshots__/index.test.js.snap
  app/components/BaseComponentStyles/layout.ts
  app/components/Switch/Switch.tsx
  app/containers/App/tests/__snapshots__/index.test.js.snap
  app/containers/CollaborationPanel/CollaborationPanel.tsx
  app/containers/CollaborationPanel/index.ts
  app/containers/CollaborationPanel/messages.ts
  app/containers/InterventionDetailsPage/Header.js
  app/containers/InterventionDetailsPage/index.js
  app/containers/LanguageProvider/index.js
  app/containers/Navbar/index.js
  app/containers/Navbar/styled.js
  app/containers/Navbar/tests/__snapshots__/index.test.js.snap
  app/containers/Navbar/tests/index.test.js
  app/containers/Sessions/components/QuestionSettings/styled.js
  app/containers/Sessions/components/QuestionSettings/tests/__snapshots__/index.test.js.snap
  app/containers/Sessions/containers/EditSessionPage/EditClassicSession.tsx
  app/containers/Sessions/containers/EditSessionPage/styled.js
  app/containers/Sessions/containers/GeneratedReportsPage/index.js
  app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/TemplateSectionSettings.js
  app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplateDetails/index.js
  app/containers/Sessions/containers/ReportTemplatesPage/components/ReportTemplatesList.js
  app/containers/Sessions/containers/ReportTemplatesPage/index.js
  app/containers/Sessions/containers/ReportTemplatesPage/tests/__snapshots__/index.test.js.snap
  app/containers/Sessions/containers/SettingsSessionPage/index.tsx
  app/containers/Sessions/containers/SettingsSessionPage/tests/__snapshots__/index.test.js.snap
  app/containers/Sessions/containers/TextMessagesPage/containers/TextMessageSettings/styled.js
  app/containers/Sessions/containers/TextMessagesPage/index.js
  app/containers/Sessions/containers/TextMessagesPage/tests/__snapshots__/index.test.js.snap
  app/global/reducers/globalState/actions.js
  app/global/reducers/globalState/constants.js
  app/global/reducers/globalState/reducer.js
  app/global/reducers/globalState/selectors.js
  app/global/reducers/intervention/selectors.js
Labels: APPROVED

#2 [CIAS30-3416] Connect collaboration UI components with BE
  app/app.tsx
  app/components/SingleNotification/components/SingleNotificationBaseLayout.tsx
  app/components/Text/Text.js
  app/containers/CollaborationPanel/CollaborationPanel.tsx
  app/containers/CollaborationPanel/messages.ts
  app/containers/InterventionChannelProvider/constants.ts
  app/containers/InterventionChannelProvider/index.tsx
  app/containers/LiveChatNavigatorPanel/index.tsx
  app/containers/NavigatorAvailabilityModal/NavigatorAvailabilityModalUI.tsx
  app/containers/NavigatorAvailabilityPanel/index.tsx
  app/containers/NotificationChannelProvider/index.tsx
  app/containers/SingleTile/index.js
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/constants.js
  app/global/reducers/intervention/reducer.js
  app/global/reducers/intervention/selectors.js
  app/models/Collaborator/index.ts
  app/models/Intervention/Editor.ts
  app/models/Intervention/Intervention.ts
  app/models/Intervention/index.ts
  app/utils/useDeepObjectMemo.ts
  app/utils/useInterventionChannel/InterventionChannelContext.ts
  app/utils/useInterventionChannel/constants.ts
  app/utils/useInterventionChannel/index.ts
  app/utils/useInterventionChannel/types.ts
  app/utils/useInterventionChannel/useInterventionChannel.ts
  app/utils/useNotificationChannel/NotificationChannelContext.ts
  app/utils/useNotificationChannel/NotificationsActionsContext.ts
  app/utils/useNotificationChannel/index.ts
  app/utils/useNotificationChannel/useNotificationChannel.ts
Labels: COMMENT, APPROVED

#6 [CIAS30-3426] Show participants data to users with access only
  app/containers/InterventionDetailsPage/components/InterventionStatusButtons/CsvButtons.js
  app/containers/InterventionDetailsPage/components/InterventionStatusButtons/index.js
  app/containers/InterventionDetailsPage/index.js
  app/containers/Navbar/components/InterventionsNavbar.js
  app/containers/SelectResearchers/index.js
  app/containers/SettingsPanel/containers/ConversationsTranscriptPanel.tsx
  app/containers/SettingsPanel/index.tsx
  app/containers/SingleTile/index.js
  app/global/reducers/intervention/selectors.js
Labels: APPROVED

#5 CIAS-3405-add-length-setting-in-numeric-question
  app/containers/AnswerSessionPage/components/tests/CharacterAnim.test.js
  app/containers/Sessions/components/QuestionDetails/tests/index.test.js
  app/containers/Sessions/components/QuestionSettings/Settings/Components/Blocks/Reflections/Reflection.js
  app/containers/Sessions/components/QuestionSettings/Settings/Components/Blocks/Reflections/ReflectionFormula.js
  app/containers/Sessions/components/QuestionSettings/Settings/Components/Blocks/SpeechBlock.js
  app/containers/Sessions/components/QuestionSettings/Settings/Components/Tabs/SettingsOption.js
  app/containers/Sessions/components/QuestionSettings/Settings/Components/Tabs/utils.js
  app/containers/Sessions/components/QuestionSettings/Settings/Components/messages.js
  app/utils/animationsHelpers/useAudioHelper.ts
  app/utils/tests/animationHelpers/useAudioHelper.test.js
Labels: APPROVED

#12 [CIAS30-3442] Fetch protected attachments form separate endpoints
  app/containers/InterventionDetailsPage/Header.js
  app/containers/InterventionDetailsPage/components/InterventionStatusButtons/CsvButtons.js
  app/containers/InterventionDetailsPage/components/InterventionStatusButtons/index.js
  app/containers/InterventionDetailsPage/index.js
  app/containers/SettingsPanel/containers/ConversationsTranscriptPanel.tsx
  app/containers/SettingsPanel/index.tsx
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/reducer.js
  app/models/Intervention/Intervention.ts
Labels: APPROVED

#13 [CIAS30-3396] Handle collaborator removed notification
  app/components/SingleNotification/components/CollaboratorRemovedNotificationLayout.tsx
  app/components/SingleNotification/index.tsx
  app/components/SingleNotification/messages.ts
  app/containers/InterventionChannelProvider/constants.ts
  app/containers/InterventionChannelProvider/index.tsx
  app/containers/Reports/components/ReportTile/index.js
  app/global/reducers/auth/selectors.js
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/constants.js
  app/global/reducers/intervention/reducer.js
  app/global/reducers/intervention/sagas/index.js
  app/global/reducers/intervention/sagas/onCollaboratorRemovedReceive.ts
  app/global/reducers/interventions/reducer.js
  app/models/Notification/Notification.ts
  app/models/Notification/NotificationData.ts
  app/models/Notification/NotificationEvent.ts
  app/theme/colors.js
  app/utils/arrayUtils.js
  app/utils/router/index.ts
  app/utils/router/matchResearchersInterventionPaths.ts
  app/utils/useConversationChannel/useConversationChannel.ts
  app/utils/useNotificationChannel/useNotificationChannel.ts
  app/utils/useSocket/useSocket.ts
Labels: READY FOR REVIEW

#14 [CIAS30-3345] Handle edit start and stop notifications
  app/assets/svg/edit-circle.svg
  app/components/CopyModal/Components/tests/__snapshots__/index.test.js.snap
  app/components/CopyModal/tests/__snapshots__/index.test.js.snap
  app/components/SingleNotification/components/StartEditingInterventionNotificationLayout.tsx
  app/components/SingleNotification/components/StopEditingInterventionNotificationLayout.tsx
  app/components/SingleNotification/components/index.ts
  app/components/SingleNotification/index.tsx
  app/components/SingleNotification/messages.ts
  app/components/Text/styled.js
  app/components/Text/tests/__snapshots__/EllipsisText.test.js.snap
  app/containers/CollaborationPanel/CollaborationPanel.tsx
  app/containers/Sessions/containers/TextMessagesPage/tests/__snapshots__/index.test.js.snap
  app/containers/SingleTile/tests/__snapshots__/index.test.js.snap
  app/models/Notification/Notification.ts
  app/models/Notification/NotificationData.ts
  app/models/Notification/NotificationEvent.ts
  package-lock.json
  package.json
Labels: READY FOR REVIEW

#15 [CIAS30-3427] Refetch data when stop editing notification received
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/constants.js
  app/global/reducers/intervention/reducer.js
  app/global/reducers/intervention/sagas/index.js
  app/global/reducers/intervention/sagas/onCollaboratorRemovedReceive.ts
  app/global/reducers/intervention/sagas/onStopEditingInterventionReceive.ts
  app/utils/useNotificationChannel/useNotificationChannel.ts
Labels: READY FOR REVIEW

#16 [CIAS30-3455] Fix app crash on intervention modules list
  .nvmrc
  app/containers/Navbar/index.js
Labels: READY FOR REVIEW

#18 [CIAS-3348] - Fix required-numeric-setting
  app/containers/AnswerSessionPage/index.js
Labels: APPROVED

#20 [CIAS30-3449] Style collaborators modal and add ellipsis
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/ResearcherRow.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/SingleCollaboratorRow.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/constants.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/index.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/styled.tsx
  app/containers/InterventionDetailsPage/index.js
  app/containers/SingleTile/index.js
Labels: READY FOR REVIEW

#21 [CIAS30-3450] Show that intervention has collaborators
  app/containers/SingleTile/index.js
Labels: READY FOR REVIEW

#22 [CIAS30-3452] Allow only intervention owner to grant data access
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/SingleCollaboratorRow.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/index.tsx
  app/containers/InterventionDetailsPage/index.js
  app/containers/SingleTile/index.js
Labels: READY FOR REVIEW

#23 [CIAS-3419] - Use simple intervention serializer
  app/global/reducers/interventions/sagas/fetchInterventions.js
  app/global/reducers/interventions/sagas/tests/fetchInterventions.test.js
  app/global/reducers/organizations/sagas/fetchOrganizationInterventions.js
  app/models/Intervention/Intervention.ts
Labels: APPROVED

#25 [CIAS-3448] - Allow empty answer in numeric question
  app/containers/AnswerSessionPage/index.js
Labels: APPROVED

#26 [CIAS30-3465] Fetch collaborator data from a separate endpoint
  app/containers/CollaborationPanel/CollaborationPanel.tsx
  app/containers/CollaborationPanel/messages.ts
  app/containers/SingleTile/index.js
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/constants.js
  app/global/reducers/intervention/messages.js
  app/global/reducers/intervention/reducer.js
  app/global/reducers/intervention/sagas/fetchCurrentUserCollaboratorData.ts
  app/global/reducers/intervention/sagas/index.js
  app/global/reducers/intervention/selectors.js
  app/models/Intervention/Intervention.ts
  app/utils/useInterventionChannel/useInterventionChannel.ts
Labels: APPROVED

#27 [CIAS-3419] - Add missing field to simple intervention interface
  app/models/Intervention/Intervention.ts
Labels: READY FOR REVIEW

#28 [CIAS30-3323] Use collaborate modal UI in share externally modal
  app/components/Text/EllipsisText.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/ResearcherRow.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/constants.ts
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/index.tsx
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/messages.ts
  app/containers/InterventionDetailsPage/index.js
  app/containers/InterventionDetailsPage/messages.js
  app/containers/SelectResearchers/ResearcherRow.tsx
  app/containers/SelectResearchers/constants.ts
  app/containers/SelectResearchers/index.js
  app/containers/SelectResearchers/index.tsx
  app/containers/SelectResearchers/messages.js
  app/containers/SelectResearchers/styled.tsx
  app/containers/SelectResearchers/tests/__snapshots__/index.test.js.snap
  app/containers/SelectResearchers/tests/index.test.js
  app/containers/Sessions/containers/EditSessionPage/EditClassicSession.tsx
  app/containers/Sessions/containers/EditSessionPage/messages.js
  app/containers/ShareExternallyModal/constants.ts
  app/containers/ShareExternallyModal/index.ts
  app/containers/ShareExternallyModal/messages.ts
  app/containers/ShareExternallyModal/useShareExternallyModal.tsx
  app/containers/SingleTile/index.js
  app/containers/SingleTile/messages.js
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/sagas/inviteCollaborator.ts
  app/global/reducers/interventions/sagas/copyIntervention.js
  app/global/reducers/interventions/sagas/tests/copyIntervention.test.js
  app/global/reducers/questionGroups/actions.js
  app/global/reducers/questionGroups/sagas/shareGroupsExternally.js
  app/global/reducers/userList/actions.js
  app/global/reducers/userList/constants.js
  app/global/reducers/userList/index.js
  app/global/reducers/userList/reducer.js
  app/global/reducers/userList/types.ts
Labels: APPROVED

#29 [CIAS30-3451] Add feature descriptions to modals
  app/containers/InterventionDetailsPage/index.js
  app/containers/InterventionDetailsPage/messages.js
  app/containers/Sessions/containers/EditSessionPage/EditClassicSession.tsx
  app/containers/ShareExternallyModal/index.ts
  app/containers/ShareExternallyModal/messages.ts
  app/containers/ShareExternallyModal/types.ts
  app/containers/ShareExternallyModal/useShareExternallyModal.tsx
  app/containers/SingleTile/index.js
  app/containers/SingleTile/messages.js
Labels: APPROVED

#30 [CIAS30-3480] Exclude intervention owner from collaborators modal
  app/containers/InterventionDetailsPage/components/Modals/CollaboratorsModal/index.tsx
  app/containers/InterventionDetailsPage/index.js
  app/containers/SingleTile/index.js
Labels: READY FOR REVIEW
