Repository Michigan-State-University/cias-web, pull requests merged in 2024-01, with the labels that each got.

#199 [CIAS30-3885] Update resources link copy
  app/containers/App/tests/__snapshots__/index.test.js.snap
  app/containers/Navbar/components/messages.js
  app/translations/en.json
Labels: READY FOR REVIEW, APPROVED

#201 [CIAS30-3886] Add hyphens automatically when typing in date
  app/components/FormikDatePicker/index.tsx
  app/components/Input/ApprovableInput.js
  app/components/Input/DateInput.tsx
  app/components/Input/constants.ts
  app/components/Input/utils.js
Labels: READY FOR REVIEW, APPROVED

#198 [CIAS30-3872] Add possibility to define the preferable communication way for PDP
  .env.example
  app/components/FormikCheckbox/index.js
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/ManagePredefinedParticipantView.tsx
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/PredefinedParticipantForm.tsx
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/PredefinedParticipantsTable.tsx
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/PredefinedParticipantsTableRow.tsx
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/SendInvitationsButtons.tsx
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/SentInvitationsInfo.tsx
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/messages.ts
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/types.ts
  app/containers/InterventionDetailsPage/containers/ParticipantInviter/utils.ts
  app/containers/InterventionDetailsPage/saga.js
  app/global/reducers/intervention/actions.js
  app/global/reducers/intervention/constants.ts
  app/global/reducers/intervention/messages.js
  app/global/reducers/intervention/reducer.js
  app/global/reducers/intervention/sagas/index.js
  app/global/reducers/intervention/sagas/sendPredefinedParticipantEmailInvitation.ts
  app/global/reducers/intervention/sagas/sendPredefinedParticipantSmsInvitation.ts
  app/global/reducers/intervention/types.ts
  app/models/PredefinedParticipant/PredefinedParticipant.ts
  app/translations/ar.json
  app/translations/en.json
Labels: DO NOT MERGE, APPROVED

#205 [CIAS30-3909] Date picker on mobile devices is covering the Date input field
  app/components/FormikDatePicker/index.tsx
  app/components/Input/ApprovableInput.js
  app/components/Input/DateInput.tsx
  app/components/Input/constants.ts
  app/components/Input/tests/__snapshots__/index.test.js.snap
  app/components/Input/utils.js
  app/containers/AnswerSessionPage/components/tests/__snapshots__/CurrencyQuestion.test.js.snap
  app/containers/AnswerSessionPage/components/tests/__snapshots__/DateQuestion.test.js.snap
  app/containers/InterventionDetailsPage/components/SessionSchedule/tests/__snapshots__/exactDate.test.js.snap
  app/containers/Sessions/components/QuestionData/DateQuestion/tests/__snapshots__/index.test.js.snap
Labels: APPROVED
